format = """
[╭](fg:current_line)\
$directory\
$git_branch\
$fill\
$cmd_duration\
$line_break\
$character\
"""

palette = 'kanagawa'
add_newline = true

[palettes.kanagawa]
foreground = '#dcd7ba'
background = '#1f1f28'
current_line = '#363646'
primary = '#2a2a37'
box = '#363646'
red = '#e46876'
green = '#98bb6c'
yellow = '#dca561'
blue = '#7fb4ca'
purple = '#957fb8'
orange = '#ffa066'

[directory]
format = '[─](fg:current_line)[](fg:purple)[󰷏 ](fg:primary bg:purple)[](fg:purple bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
truncation_length = 0

[git_branch]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $branch](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[fill]
symbol = '─'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[─](fg:current_line)[](fg:orange)[󰔛 ](fg:primary bg:orange)[](fg:orange bg:box)[ $duration ](fg:foreground bg:box)[](fg:box)'

[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = "[\\[I\\]](bold green)"
error_symbol = "[\\[I\\]](bold green)"
vicmd_symbol = "[\\[N\\]](bold blue)"
vimcmd_replace_one_symbol = "[\\[R\\]](bold red)"
vimcmd_replace_symbol = "[\\[R\\]](bold red)"
vimcmd_visual_symbol = "[\\[V\\]](bold yellow)"
